services:
  web_api:
    container_name: mermaid-chatgpt-editor-web-api
    build:
      context: ./
      dockerfile: ./service/webApi/docker/Dockerfile
    tty: true
    volumes:
      - ./service/webApi/src:/app
      - mermaid-chatgpt-editor-ma-nm:/app/node_modules
    command: sh -c "yarn run start"
    ports:
      - 10.0.0.2:31501:31501

volumes:
  mermaid-chatgpt-editor-ma-nm:

